version: '3'

vars:
  PROTO_DIR: "proto/sso"
  OUTPUT_DIR: "./gen/go"
  PROTO_FILE: "sso.proto"

tasks:
  default:
    desc: Генерирует Go и gRPC код из proto файлов
    cmds:
      - task: generate

  generate:
    desc: Генерирует Go и gRPC код
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}
      - protoc -I={{.PROTO_DIR}} --go_out={{.OUTPUT_DIR}} --go_opt=paths=source_relative --go-grpc_out={{.OUTPUT_DIR}} --go-grpc_opt=paths=source_relative {{.PROTO_DIR}}/{{.PROTO_FILE}}